// Mock event data for testing API integration
export const mockEvents = [
  {
    id: 'evt1',
    title: 'Blockchain Summit 2025',
    description: 'A premier conference on blockchain technology and decentralized applications.',
    date: '2025-06-15',
    location: 'Bangalore International Exhibition Centre, Bengaluru',
    price: 1500,
    status: 'upcoming',
    image: '/event-images/blockchain-summit.jpg',
    organizer: 'Priya Singh',
    ticketsAvailable: 200,
  },
  {
    id: 'evt2',
    title: 'Mumbai Music Carnival',
    description: 'Experience the best of Indian music with renowned artists and bands.',
    date: '2025-07-20',
    location: 'MMRDA Grounds, Mumbai',
    price: 1200,
    status: 'upcoming',
    image: '/event-images/music-carnival.jpg',
    organizer: 'Sneha Patel',
    ticketsAvailable: 350,
  },
  {
    id: 'evt3',
    title: 'Delhi Tech Expo',
    description: 'Showcasing the latest in technology, gadgets, and innovation.',
    date: '2025-08-10',
    location: 'Pragati Maidan, New Delhi',
    price: 900,
    status: 'upcoming',
    image: '/event-images/tech-expo.jpg',
    organizer: 'Amit Sharma',
    ticketsAvailable: 500,
  },
  {
    id: 'evt4',
    title: 'Hyderabad Startup Meetup',
    description: 'Connect with founders, investors, and mentors in the Indian startup ecosystem.',
    date: '2025-05-28',
    location: 'HICC, Hyderabad',
    price: 600,
    status: 'upcoming',
    image: '/event-images/startup-meetup.jpg',
    organizer: 'Rahul Verma',
    ticketsAvailable: 100,
  },
  {
    id: 'evt5',
    title: 'Chennai Art Festival',
    description: 'A celebration of art, culture, and creativity in the heart of Chennai.',
    date: '2025-09-05',
    location: 'Cholamandal Artists’ Village, Chennai',
    price: 700,
    status: 'upcoming',
    image: '/event-images/art-festival.jpg',
    organizer: 'Ananya Iyer',
    ticketsAvailable: 250,
  },
];
